# 4) French greeting: correctness + tone + (cheap OR fast)
description: "Require a friendly French greeting that includes 'Bonjour' and stays within budget (either cheap or fast)."
providers:
  - openai:gpt-5

prompts:
  - "Greet the user in French."

tests:
  - threshold: 0.6
    assert:
      - type: contains
        value: "Bonjour"
        weight: 2
        metric: Correctness
      - type: llm-rubric
        value: "Tone is friendly and the text is in French."
        weight: 1
        metric: Tone
      - type: answer-relevance
        threshold: 0.8
        weight: 1
        metric: Topicality
      - type: llm-rubric
        value: "The response is engaging and appropriate for a friendly greeting."
        threshold: 0.8
        weight: 1
        metric: Greeting  
      - type: assert-set
        threshold: 0.6
        metric: Performance
        weight: 2
        assert:
          - type: cost
            threshold: 0.0000001
          - type: latency
            threshold: 150
    assertScoringFunction: file://./override.py:calculate_score
        